### ISSUE TITLE
Can't disable hunger regen in peaceful (1.12.2)

### ISSUE THREAD

**Issue by cody-greene** [coolsquid/HungerTweaker#1]
I tried to replicate the ["Hunger in Peace" mod](https://github.com/squeek502/HungerInPeace/blob/3cdebe739596e2ffa54a7987a845bcb48d7c28b5/java/squeek/hungerinpeace/HungerInPeace.java) just using HungerTweaker instead. But given the following script... the hunger bar still fills up quickly when in peaceful mode. Which means health always regens anyway.
```
#modloaded hungertweaker
import mods.hungertweaker.events.ExhaustedEvent;
import mods.hungertweaker.events.HungerEvents;
import mods.hungertweaker.events.PeacefulRegenEvent;
import mods.hungertweaker.events.StarveEvent;

static PEACEFUL as string = "PEACEFUL";
static STARVE_MIN_HEALTH as float = 1.0;

HungerEvents.onExhausted(function (evt as ExhaustedEvent) {
  if (evt.player.world.worldInfo.difficulty != PEACEFUL) {
    return;
  }
  if (evt.player.foodStats.saturationLevel <= 0) {
    evt.deltaHunger = -1;
  }
});
HungerEvents.onPeacefulRegen(function (evt as PeacefulRegenEvent) {
  evt.cancel();
});
HungerEvents.onStarve(function (evt as StarveEvent) {
  if (evt.starveDamage != 0.0) {
    return;
  }
  if (evt.player.world.worldInfo.difficulty != PEACEFUL) {
    return;
  }
  if (evt.player.health <= STARVE_MIN_HEALTH) {
    return;
  }
  evt.starveDamage = 1.0;
});
```

**Comment by coolsquid** [comment]
AppleCore provides two separate events named "PeacefulRegen", which affect hunger regen and health regen, respectively. Due to an oversight, HungerTweaker only implements the health regen event.

**Comment by coolsquid** [comment]
That should fix the problem. I'll upload a new version to CurseForge and GitHub later today.

**Comment by coolsquid** [comment]
I just uploaded version 1.2.0 to CurseForge and GitHub. The new version has a "PeacefulHungerRegenEvent" that can be used to control hunger regen in peaceful mode. It functions exactly like "PeacefulRegenEvent", but uses "deltaHunger" instead of "deltaHealth".

**Comment by cody-greene** [comment]
Fantastic
