### ISSUE TITLE
Hunger Doesnt Seem To Be Changing

### ISSUE THREAD

**Issue by Boolyman** [coolsquid/HungerTweaker#2]
I am tweaking values pretty drastically in my script, because I want hunger to be a bigger factor... but players of my pack dont see any noticeable increase in hunger.  Is my script not formatted properly?   Is there a way to just cause a constant mild hunger loss?  I know Hunger Overhaul can do it, but I don't want to implement all the other invasive changes that mod makes.

My script:
mods.hungertweaker.ExhaustingAction.HARVEST_BLOCK.setDeltaExhaustion("x*2");
mods.hungertweaker.ExhaustingAction.NORMAL_JUMP.setDeltaExhaustion("x*2");
mods.hungertweaker.ExhaustingAction.SPRINTING_JUMP.setDeltaExhaustion("x*2");
mods.hungertweaker.ExhaustingAction.ATTACK_ENTITY.setDeltaExhaustion("x*2");
mods.hungertweaker.ExhaustingAction.DAMAGE_TAKEN.setDeltaExhaustion("x*4");
mods.hungertweaker.ExhaustingAction.HUNGER_POTION.setDeltaExhaustion("x*4");
mods.hungertweaker.ExhaustingAction.MOVEMENT_DIVE.setDeltaExhaustion("x*4");
mods.hungertweaker.ExhaustingAction.MOVEMENT_SWIM.setDeltaExhaustion("x*5");
mods.hungertweaker.ExhaustingAction.MOVEMENT_SPRINT.setDeltaExhaustion("x*2");
mods.hungertweaker.ExhaustingAction.MOVEMENT_CROUCH.setDeltaExhaustion("x*2");
mods.hungertweaker.ExhaustingAction.MOVEMENT_WALK.setDeltaExhaustion("x*4");

**Comment by coolsquid** [comment]
I can't reproduce the issue. Try to multiply the values by a large number (e.g. 50), and walk around. If your hunger still depletes slowly, then something is wrong. Otherwise, factors of 2-5 might simply be too small.
>Is there a way to just cause a constant mild hunger loss?

I just uploaded v.1.3.0, which can set a constant exhaustion increase. The increase is applied every tick.
`mods.hungertweaker.Exhaustion.setConstantExhaustionIncrease(0.05);`

**Comment by Boolyman** [comment]
I apologize, but I am crunched for time to get this pack out, and I didnt see a response for a few days, so I swapped out this mod for Hunger Overhaul just to get the constant mild hunger loss.  So I can't do any further testing of this at the moment.
