### ISSUE TITLE
Add passive hunger drain feature

### ISSUE THREAD

**Issue by Flypaste** [coolsquid/HungerTweaker#4]
^^ please and thanks :)

**Comment by coolsquid** [comment]
This already exists, though I haven't documented it yet.

    mods.hungertweaker.Exhaustion.setConstantExhaustionIncrease(0.05);

This example applies 0.05 exhaustion every tick. If I recall correctly, the player's hunger value will, by default, decrease by 1 (half a drumstick) when the exhaustion level reaches 4.
