### ISSUE TITLE
saturationModifier doesn't work or i don't understand something.

### ISSUE THREAD

**Issue by Blatts12** [coolsquid/HungerTweaker#5]
So, I wrote little class to change food values.

https://pastebin.com/zSzeAx7k

`foodChanger.setNewValues(2, 2.5, <quark:cooked_frog_leg>);`
This line of code should change hunger to 2 and saturation to 2.5 but it doesn't work.

I get hunger 2 and saturation ~1.5.
https://i.imgur.com/VMyP8v7.png

HungerTweaker 1.3.0
AppleCore 3.4.0
CraftTweaker 4.1.20.574

**Comment by coolsquid** [comment]
I appear to have made a mistake when I documented the "saturationModifier" property. The documentation states that the saturation added is equal to "the food's hunger value * the food's saturation modifier * 2", but the "* 2" part is incorrect.

You should get the correct saturation if you change

    ingredient.foodValues.saturationModifier = saturation / (hunger * 2);

to

    ingredient.foodValues.saturationModifier = saturation / hunger;

I will fix the documentation in a moment. Thanks for the report!
